[우선순위 큐] 4월 1일 첫 번째 제출
Altu-Bitu-2/Altu-Bitu_MinJung pull request #9
Opened 2022-04-07 02:58 UTC by wowalswjd

#### 내용 & 질문
> 13975번은 답이 틀렸다고 나와서 오늘 자정까지 고쳐서 다시 제출하도록 하겠습니다!

#### <기존 제출>
> 5397, 13975, 14235

#### <추가 제출>
> 2075, 7662

2022-04-08 11:20 UTC, ZERO-black requested changes

2022-04-08 11:20 UTC, ZERO-black commented on [우선순위 큐] 4월 1일/priority_13975.py
> +        file_list.pop(0)
p1. pop(0)은 리스트의 가장 앞 원소를 제거한 후에 뒤쪽의 모든 원소들을 한칸 씩 앞으로 당겨옵니다. 따라서 O(n)의 시간복잡도를 갖기 때문에, 삭제가 여러번 이루어지는 경우, 다른 자료구조(컨테이너)를 사용하셔야 합니다!

2022-04-08 11:20 UTC, ZERO-black commented on [우선순위 큐] 4월 1일/priority_13975.py
> +        file_list.sort()
p1. 지금 모든 테스트케이스마다 k-1번씩 정렬을 해주고 있어요! 이렇게 매번 새로 정렬을 하면 대략적으로 k*(t-1)번의 정렬이 이루어진다고 보면 되는데, 이것도 역시 시간 부담이 크겠죠? 현재 가장 작은 원소를 계속 삭제해야 하는 상황인데, 이것에 유리한 자료구조를 활용하면 좋을거 같아요!

2022-04-08 11:23 UTC, ZERO-black reviewed
필수 1/2문제, 선택 1/5문제 확인되셨습니다! 피드백이 늦어 죄송합니다.
코드리뷰가 늦었던 관계로, 13975문제는 내일(4/9일) 자정까지 수정하시면 제출인정 해드릴게요! 나머지 문제는 오늘 자정까지 추가제출 해주시면 됩니다😊
수정하시고 저 다시 리뷰어로 호출해주세요!

2022-04-08 11:23 UTC, ZERO-black commented on [우선순위 큐] 4월 1일/priority_14235.py
> +            print(-present) # -붙여서 삽입했었기 때문에 -붙여서 출력
음수를 붙여서 최대힙으로 만들어준 부분 좋아요👍

2022-04-08 11:23 UTC, ZERO-black commented on [우선순위 큐] 4월 1일/priority_5397.py
> +right = deque() # 커서 뒤 -> 시간 초과로 deque로 변경
아마 여기서 시간초과가 난 이유도 13975문제와 마찬가지로 pop(0)의 시간복잡도가 O(n)이기 때문이었을 거에요!

2022-04-08 14:49 UTC, wowalswjd commented
오 그러면 13975번 문제는 9일 자정까지 꼭 수정하도록 하겠습니다! 나머지 2문제는 추가제출했습니다 :)

2022-04-09 14:40 UTC, wowalswjd commented on [우선순위 큐] 4월 1일/priority_13975.py
> +        file_list.sort()
가장 작은 원소를 계속 삭제해야 한다 -> 여기서 최소 힙이 떠올라서 바로 자료구조 변경했더니 맞았습니다가 떴습니다!! 알려주셔서 감사해요🥰

2022-04-10 19:03 UTC, ZERO-black requested changes
추가 제출과, 수정 코드까지 확인해서 전체 필수 2/2문제, 선택 3/5문제 확인되셨습니다👍👍
최소 힙으로 바꿔서 시간 초과 잘 해결해주셨는데, 반복문 변수 사용 관련해서 작은 실수 하나 하셔서 코멘트 드렸습니다. 실수 자체는 사소한데, 이런 실수는 막상 오류가 나면 크게 나고, 또 은근히 찾기도 어려워서 p1태그 드렸습니다. 수정하시고 편하게 머지하셔도 됩니다😍

2022-04-10 19:03 UTC, ZERO-black commented on [우선순위 큐] 4월 1일/priority_13975.py
> +    for i in range(k-1): # k-1번 동안 반복(2개 pop하고 pop한 값 2개 더해서 다시 push하는 방식)
p1. 지금 바깥쪽 반복문에 사용한 변수와, 안쪽 반복문에 사용한 변수가 i로 같아요! 지금 코드에서는 i를 쓰지 않아서 오류가 나지 않았지만, 만약 안쪽에서 i를 사용했다면, 의도와는 전혀 다른 실행결과를 보실 수도 있습니다.
반복문을 쓰실 때 이미 사용하고 있는 변수를 사용하지 않도록 주의해주세요!!!

+) 이럴 때 사용할 수 있는 이름으로 `_`가 있습니다. 이후에 사용하지 않을 변수에도 전부 이름을 부여하면 변수가 많아지고, 지금처럼 이름이 겹쳐서 오류가 날 수도 있겠죠!! 따라서, 이름을 따로 부여하고 싶지 않을 때 `_` 를 사용할 수 있어요. 예를 들어 반복문에서는 `for _ in range(n)` 와 같이 사용합니다. n번 반복하지만, 현재 반복 횟수가 쓰이지 않을 때 이렇게 사용할 수 있어요😊

2022-04-10 19:43 UTC, wowalswjd commented on [우선순위 큐] 4월 1일/priority_13975.py
> +    for i in range(k-1): # k-1번 동안 반복(2개 pop하고 pop한 값 2개 더해서 다시 push하는 방식)
오 진짜 i를 사용하는 경우였으면 또 오류날 뻔 했네요😂 
수정했고 머지하도록 하겠습니다!
알려주셔서 감사해요🥰

2022-04-10 19:44 UTC, merged